### ISSUE TITLE
Rules based on OWASP 2017 RC1, update to OWASP 2017 Final? 

### ISSUE THREAD

**Issue by autodeck** [binbashar/terraform-aws-waf-owasp#5]
As far as I can tell, the rules seem to be based most closely on the RC1 version of the OWASP 2017 Top 10:
https://www.owasp.org/images/3/3c/OWASP_Top_10_-_2017_Release_Candidate1_English.pdf

Are there any plans to update to the final version:
https://www.owasp.org/images/7/72/OWASP_Top_10-2017_%28en%29.pdf.pdf

**Comment by exequielrafaela** [comment]
@autodeck thanks for your improvement request here, we'll most probably consider it and add it in our roadmap for this next few months. 

If your requirement is urgent do not leave out of consideration the brand new (Nov 2019) `wafv2` **Managed rules for AWS Web Application Firewall**: AWS WAF announces AWS Managed Rules (AMRs), a set of AWS WAF rules curated and maintained by the AWS Threat Research Team: 

- https://aws.amazon.com/blogs/aws/announcing-aws-managed-rules-for-aws-waf/
  
**NOTE1:** Currently this new WAF version it's not supported by the `terraform-aws-provider` they're WIP though :muscle: ->  https://github.com/terraform-providers/terraform-provider-aws/issues/11046

**NOTE2:** Currently supported as code via:
- https://docs.aws.amazon.com/cli/latest/reference/wafv2/index.html
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/wafv2.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-webacl.html

CC: @diego-ojeda-binbash @mpagnucco @gdmlnx @AlfredoPardo

**Comment by autodeck** [comment]
@exequielrafaela - Sorry for the delay - great news :) I'll keep an eye on this! 

Yes I did consider the wafv2 - but as you imply - I need to be able to Terraform it.
Thanks

**Comment by exequielrafaela** [comment]
@autodeck we'll be favouring `wafv2` since terraform support is already here:

### aws provider resources
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_ip_set
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_regex_pattern_set
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_rule_group
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_association
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_logging_configuration

### Reference Module 
* https://registry.terraform.io/modules/umotif-public/waf-webaclv2/aws/1.4.0

Thanks for your time and collab here!

CC: @diego-ojeda-binbash
